# fly.toml app configuration file generated for nobetciyim on 2025-06-10T12:34:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nobetciyim'
primary_region = 'ams'

[build]

[env]
  PORT = '80'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['node app.js']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
