# fly.toml app configuration file generated for nobetciyim on 2025-06-12T16:23:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nobetciyim'
primary_region = 'fra'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PORT = '80'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  
[checks]
  [checks.name_of_your_tcp_check]
    grace_period = "30s"
    interval = "15s"
    port = 80
    timeout = "10s"
    type = "tcp"
	
[mounts]
	source = "vnobetci"
	destination = "/data"

