# fly.toml app configuration file for nobetciyim Node.js application
app = 'nobetciyim'
primary_region = 'fra'

[build]

[env]
  PORT = '80'
  NODE_ENV = 'development'
  CRON_DEBUG_LOGGING = 'true'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[vm]
  size = 'shared-cpu-1x'
  memory = 512

[mounts]
  source = "vnobetci"
  destination = "/app/data"